# Generated by Django 6.0.8 on 2026-08-24 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidate_photos/')),
                ('bio', models.TextField(blank=True, default='')),
                ('availability', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=100)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('specialization_name', models.CharField(blank=True, default='', max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='candidates.candidateprofile')),
            ],
            options={
                'ordering': ['-years_of_experience'],
            },
        ),
        migrations.CreateModel(
            name='LicenseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50)),
                ('issuing_body', models.CharField(default='Kerala Nurses and Midwives Council', max_length=200)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='candidates.candidateprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('GNM', 'GNM (General Nursing and Midwifery)'), ('BSC', 'B.Sc Nursing'), ('MSC', 'M.Sc Nursing'), ('PHD', 'Ph.D Nursing'), ('DIPLOMA', 'Diploma in Nursing'), ('POST_BASIC', 'Post Basic B.Sc Nursing'), ('OTHER', 'Other')], max_length=20)),
                ('institution', models.CharField(max_length=200)),
                ('year_of_completion', models.PositiveIntegerField()),
                ('grade', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='candidates.candidateprofile')),
            ],
            options={
                'ordering': ['-year_of_completion'],
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digilocker_status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_submitted', max_length=20)),
                ('knmc_status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='not_submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('digilocker_verified_at', models.DateTimeField(blank=True, null=True)),
                ('knmc_verified_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='candidates.candidateprofile')),
            ],
            options={
                'verbose_name_plural': 'verification requests',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ICU', 'ICU / Critical Care'), ('GENERAL', 'General Nursing'), ('PEDIATRIC', 'Pediatric Nursing'), ('CARDIAC', 'Cardiac Care'), ('ONCOLOGY', 'Oncology Nursing'), ('EMERGENCY', 'Emergency / Trauma'), ('OPERATING_ROOM', 'Operating Room / Surgical'), ('COMMUNITY', 'Community Health'), ('MENTAL_HEALTH', 'Mental Health / Psychiatric'), ('OBSTETRIC', 'Obstetric / Maternity'), ('NEONATAL', 'Neonatal Care'), ('ORTHOPEDIC', 'Orthopedic Nursing'), ('NEPHROLOGY', 'Nephrology / Dialysis'), ('OTHER', 'Other')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='candidates.candidateprofile')),
            ],
            options={
                'verbose_name_plural': 'specializations',
                'unique_together': {('candidate', 'name')},
            },
        ),
    ]
