# Generated by Django 6.0.8 on 2026-09-20 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('profile_photo', 'Profile Photo'), ('registration_certificate', 'Registration Certificate'), ('qualification_certificate', 'Qualification Certificate')], max_length=30)),
                ('document', models.FileField(upload_to='candidate_documents/%Y/%m/%d/')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='candidates.candidateprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('candidate', 'document_type')},
            },
        ),
    ]
