# Generated by Django 6.0.8 on 2026-08-24 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('position_type', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('min_qualification', models.CharField(choices=[('GNM', 'GNM'), ('BSC', 'B.Sc Nursing'), ('MSC', 'M.Sc Nursing'), ('POST_BASIC', 'Post Basic B.Sc Nursing'), ('DIPLOMA', 'Diploma in Nursing'), ('ANY', 'Any')], default='ANY', max_length=20)),
                ('min_experience', models.PositiveIntegerField(default=0, help_text='Minimum years of experience')),
                ('specialization', models.CharField(choices=[('ICU', 'ICU / Critical Care'), ('GENERAL', 'General Nursing'), ('PEDIATRIC', 'Pediatric Nursing'), ('CARDIAC', 'Cardiac Care'), ('ONCOLOGY', 'Oncology Nursing'), ('EMERGENCY', 'Emergency / Trauma'), ('OPERATING_ROOM', 'Operating Room / Surgical'), ('COMMUNITY', 'Community Health'), ('MENTAL_HEALTH', 'Mental Health / Psychiatric'), ('OBSTETRIC', 'Obstetric / Maternity'), ('NEONATAL', 'Neonatal Care'), ('ORTHOPEDIC', 'Orthopedic Nursing'), ('NEPHROLOGY', 'Nephrology / Dialysis'), ('OTHER', 'Other'), ('ANY', 'Any')], default='ANY', max_length=30)),
                ('license_required', models.BooleanField(default=True)),
                ('additional_criteria', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shortlisted', 'Shortlisted'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shortlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shortlists', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlists', to='recruitment.recruitmentrequirement')),
            ],
        ),
        migrations.CreateModel(
            name='ShortlistedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlistings', to='candidates.candidateprofile')),
                ('shortlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='recruitment.shortlist')),
            ],
            options={
                'unique_together': {('shortlist', 'candidate')},
            },
        ),
    ]
